const PALETTE = [
  ['奶油白','#fff8e7'],['象牙白','#f6f0d8'],['浅黄','#f9d86b'],['暖橙','#f39a4a'],['珊瑚红','#ed6a5a'],['莓果红','#c94662'],
  ['薄荷绿','#a8d8b9'],['叶子绿','#65a878'],['森林绿','#34745a'],['天蓝','#83c5e8'],['海军蓝','#31547d'],['紫罗兰','#9b78c8'],
  ['焦糖棕','#a8734e'],['可可棕','#6f4b3a'],['深棕','#51362d'],['浅棕','#c28a5b'],['炭黑','#252831'],['深灰','#4b515c'],['中灰','#7f8792'],['雾灰','#a9afb8'],['浅灰','#d3d7dc'],['粉白','#f4d8cf'],['浅粉','#e8a7ad'],['深黄','#d9ad3a'],['亮黄','#ffe27a'],['青绿','#4e9b82'],['浅青','#b8e3cf'],['深蓝','#243f67']
];
const COLOR_CODES=['C12','C18','C29','C28','D1','E14','F11','F17','G8','G17','G3','G9','G16','H16','H6','H5','H13','H17','H19','H7','M7','M15','M9','M13','M20','M21','M22','M23','M24','M25','M26','M27'];
const state = { image:null, cols:64, zoom:1, palette:PALETTE, grid:true, round:false, codes:false, bg:'#ffffff', pixels:[] };
const app = document.querySelector('#app');
const redeemBar = document.createElement('div'); redeemBar.className='redeem-bar'; redeemBar.innerHTML='<input id="redeemCode" placeholder="输入兑换码"><button id="redeemBtn">验证兑换码</button><span id="redeemStatus">未验证</span>'; app.before(redeemBar);
app.innerHTML = `<header><div class="brand"><span class="brand-mark">✦</span><div><b>拼豆图纸工坊</b><small>PEARL PIXEL STUDIO</small></div></div><span class="status"><i></i> 本地处理 · 图片不上传</span></header>
<main><section class="hero"><div><p class="eyebrow">MAKE IT BEAD-BY-BEAD</p><h1>把喜欢的图片，<em>变成拼豆图纸。</em></h1><p class="intro">上传一张图片，几秒钟得到可打印、可照着拼的彩色点阵图。所有处理均在你的设备上完成。</p></div><div class="hero-note"><strong>16 色基础方案</strong><span>更贴近常见拼豆色卡</span></div></section>
<div class="workspace"><aside class="panel controls"><div class="panel-title"><span>01</span><h2>准备图片</h2></div><label class="dropzone" id="dropzone"><input id="file" type="file" accept="image/png,image/jpeg,image/webp"/><div class="upload-icon">＋</div><b>点击上传图片</b><span>或拖拽图片到这里</span><small>支持 JPG / PNG / WEBP · 建议正方形</small></label><div class="field"><label>图纸宽度 <output id="colsOut">32</output> 颗</label><input id="cols" type="range" min="12" max="80" value="32"/><div class="range-label"><span>精细</span><span>细节丰富</span></div></div><div class="field"><label>背景颜色</label><div class="color-row"><button class="swatch active" data-bg="#ffffff" style="background:#fff"></button><button class="swatch" data-bg="#f6f0d8" style="background:#f6f0d8"></button><button class="swatch" data-bg="#252831" style="background:#252831"></button><input id="bg" type="color" value="#ffffff"/></div></div><div class="toggle-row"><span>显示网格线 <small>方便数格</small></span><button class="toggle on" id="gridToggle"><i></i></button></div><div class="toggle-row"><span>圆豆预览 <small>模拟成品效果</small></span><button class="toggle" id="roundToggle"><i></i></button></div><button class="primary" id="generate">生成拼豆图纸 <span>⌘ ↵</span></button><p class="tip">建议：主体清晰、颜色对比明显的图片效果最佳。</p></aside>
<section class="panel preview-panel"><div class="panel-title"><span>02</span><h2>预览与导出</h2><div class="actions"><button id="reset">↺ 重置</button><button class="export" id="export">↓ 下载 PNG</button></div></div><div class="canvas-wrap" id="canvasWrap"><div class="empty"><div>✧</div><b>你的拼豆图纸会出现在这里</b><span>上传图片后点击「生成拼豆图纸」</span></div><canvas id="canvas"></canvas></div><div class="legend"><div><span class="legend-dot"></span><b id="sizeLabel">32 × 32</b><small>图纸尺寸</small></div><div><span class="legend-dot pink"></span><b id="beadLabel">1,024</b><small>拼豆数量</small></div><div><span class="legend-dot blue"></span><b>16 色</b><small>匹配色卡</small></div></div></section></div>
<section class="how"><div><span class="step">A</span><b>上传图片</b><p>选择你想制作的照片或插画</p></div><div class="line"></div><div><span class="step">B</span><b>调整参数</b><p>按作品大小和细节需求调节</p></div><div class="line"></div><div><span class="step">C</span><b>开始拼吧</b><p>下载图纸，照着颜色逐格完成</p></div></section></main><footer>© 2025 Pearl Pixel Studio <span>专为热爱创造的你</span></footer>`;

const $ = s => document.querySelector(s); const canvas = $('#canvas'); const ctx = canvas.getContext('2d'); $('#cols').value=state.cols; $('#colsOut').textContent=state.cols; const colorList=document.createElement('div'); colorList.className='color-list'; colorList.innerHTML='<div class="color-list-head"><b>颜色清单</b><span>MARD 拼豆 · 按数量排序</span></div>'; const previewPanel=document.querySelector('.preview-panel'); previewPanel.appendChild(colorList); const controlsPanel=document.querySelector('.controls'), workspace=document.querySelector('.workspace'); const arrangePreview=()=>{if(innerWidth<=760&&previewPanel.parentElement!==controlsPanel)controlsPanel.appendChild(previewPanel);else if(innerWidth>760&&previewPanel.parentElement!==workspace)workspace.appendChild(previewPanel)}; arrangePreview(); addEventListener('resize',arrangePreview);
function nearest(r,g,b){ let best=PALETTE[0][1], d=1e9; for(const [,hex] of PALETTE){const q=hex.match(/\w\w/g).map(x=>parseInt(x,16)); const x=(r-q[0])**2+(g-q[1])**2+(b-q[2])**2;if(x<d){d=x;best=hex}} return best; }
function render(){ if(!state.image){$('#canvas').style.display='none';$('.empty').style.display='flex';return} $('.empty').style.display='none';canvas.style.display='block'; const n=state.cols, size=18; canvas.width=n*size;canvas.height=n*size; ctx.fillStyle=state.bg;ctx.fillRect(0,0,canvas.width,canvas.height);
  const sample=document.createElement('canvas'); sample.width=sample.height=n; const sampleCtx=sample.getContext('2d'); const side=Math.min(state.image.width,state.image.height); const sx=(state.image.width-side)/2, sy=(state.image.height-side)/2; sampleCtx.drawImage(state.image,sx,sy,side,side,0,0,n,n); const data=sampleCtx.getImageData(0,0,n,n).data; state.pixels=[];
  const counts={}; for(let y=0;y<n;y++){state.pixels[y]=[];for(let x=0;x<n;x++){const i=(y*n+x)*4; let r=data[i],g=data[i+1],b=data[i+2]; const spread=Math.max(r,g,b)-Math.min(r,g,b); if(spread<34){const gray=(r+g+b)/3;r=g=b=gray} const contrast=1.12; r=Math.max(0,Math.min(255,(r-128)*contrast+128));g=Math.max(0,Math.min(255,(g-128)*contrast+128));b=Math.max(0,Math.min(255,(b-128)*contrast+128)); const hex=nearest(r,g,b);state.pixels[y][x]=hex;counts[hex]=(counts[hex]||0)+1;ctx.fillStyle=hex; if(state.round){ctx.beginPath();ctx.arc(x*size+size/2,y*size+size/2,8,0,Math.PI*2);ctx.fill()}else ctx.fillRect(x*size,y*size,size,size); if(state.codes && size>=14){const idx=PALETTE.findIndex(p=>p[1]===hex);const code=COLOR_CODES[idx]||String(idx+1).padStart(2,'0');ctx.fillStyle=((r+g+b)/3>155)?'rgba(20,25,35,.62)':'rgba(255,255,255,.72)';ctx.font='7px DM Mono';ctx.fillText(code,x*size+2,y*size+10)} if(state.grid){ctx.strokeStyle='rgba(40,45,60,.16)';ctx.strokeRect(x*size,y*size,size,size)}}} const items=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([hex,count])=>{const idx=PALETTE.findIndex(p=>p[1]===hex);return `<div class="color-item"><i style="background:${hex}"></i><b>${COLOR_CODES[idx]||idx+1}</b><span>${count} 颗</span></div>`}).join('');colorList.innerHTML='<div class="color-list-head"><b>颜色清单</b><span>MARD 拼豆 · '+Object.keys(counts).length+' 色</span></div><div class="color-items">'+items+'</div>'; $('#sizeLabel').textContent=`${n} × ${n}`;$('#beadLabel').textContent=(n*n).toLocaleString(); }
function load(fileOrUrl){const img=new Image();img.onload=()=>{state.image=img;const waiting=typeof fileOrUrl!=='string'&&location.protocol!=='file:'&&window.pearlAutoEnhance;if(waiting){$('#canvas').style.display='none';$('.empty').style.display='flex';$('.empty b').textContent='AI 精致像素生成中…';$('.empty span').textContent='正在分析主体、清理背景并生成拼豆图纸'}else render();if(typeof fileOrUrl!=='string'&&window.pearlAutoEnhance)setTimeout(window.pearlAutoEnhance,80)};img.onerror=()=>alert('图片加载失败，请检查 AI 返回结果');img.src=typeof fileOrUrl==='string'?fileOrUrl:URL.createObjectURL(fileOrUrl)}
const acceptUpload=e=>{if(!window.pearlRequireRedeem||!window.pearlRequireRedeem()){e.preventDefault();if(e.target?.tagName==='INPUT')e.target.value='';return false}return true};
$('#file').onchange=e=>{if(acceptUpload(e)&&e.target.files[0])load(e.target.files[0])}; $('#dropzone').ondragover=e=>{e.preventDefault();if(window.pearlRequireRedeem&&!window.pearlRequireRedeem())return;$('#dropzone').classList.add('drag')};$('#dropzone').ondragleave=()=>$('#dropzone').classList.remove('drag');$('#dropzone').ondrop=e=>{e.preventDefault();$('#dropzone').classList.remove('drag');if(acceptUpload(e)&&e.dataTransfer.files[0])load(e.dataTransfer.files[0])};
$('#cols').oninput=e=>{$('#colsOut').textContent=e.target.value;state.cols=+e.target.value; if(state.image)render()}; $('#generate').onclick=render; $('#gridToggle').onclick=e=>{state.grid=!state.grid;e.currentTarget.classList.toggle('on');render()};$('#roundToggle').onclick=e=>{state.round=!state.round;e.currentTarget.classList.toggle('on');render()}; document.querySelectorAll('[data-bg]').forEach(b=>b.onclick=()=>{state.bg=b.dataset.bg;document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});$('#bg').oninput=e=>{state.bg=e.target.value;render()};$('#reset').onclick=()=>{state.image=null;$('#file').value='';render()};$('#export').onclick=()=>{if(!state.image){alert('请先上传图片');return} const a=document.createElement('a');a.download=`拼豆图纸-${state.cols}x${state.cols}.png`;a.href=canvas.toDataURL('image/png');a.click()};
const aiButton=document.createElement('button'); aiButton.className='ai-enhance'; aiButton.textContent='✦ AI 卡通像素精修（可选）'; document.querySelector('.controls').insertBefore(aiButton,document.querySelector('#generate'));
const codeButton=document.createElement('button'); codeButton.className='code-toggle'; codeButton.textContent='▦ 显示色号（数格模式）'; document.querySelector('.controls').insertBefore(codeButton,document.querySelector('#generate')); codeButton.onclick=()=>{state.codes=!state.codes;codeButton.textContent=state.codes?'▦ 隐藏色号（看图模式）':'▦ 显示色号（数格模式）';render()};
aiButton.onclick=async()=>{if(!state.image){alert('请先上传图片');return}if(location.protocol==='file:'){alert('AI 精修需要通过 Node/Vercel 服务运行；当前本地模式会继续使用免费算法。');return}aiButton.disabled=true;let seconds=0;aiButton.textContent='分析图片中…';const progress=setInterval(()=>{seconds++;aiButton.textContent=seconds<12?'分析图片中…':seconds<35?'生成像素图中…':`仍在生成中（${seconds}s）…`},1000);try{const temp=document.createElement('canvas');temp.width=temp.height=768;const t=temp.getContext('2d'),side=Math.min(state.image.width,state.image.height);t.drawImage(state.image,(state.image.width-side)/2,(state.image.height-side)/2,side,side,0,0,768,768);const res=await fetch('/api/enhance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:temp.toDataURL('image/jpeg',.76),style:window.pearlPixelStyle||'精致像素'})});const data=await res.json();if(!res.ok)throw new Error(data.error||`服务端错误 ${res.status}`);if(!data.imageUrl)throw new Error('接口没有返回图片');load(data.imageUrl);aiButton.textContent='✦ AI 精修完成'}catch(error){render();aiButton.textContent='AI 暂不可用 · 已保留本地结果';alert(`AI 服务调用失败：${error.message}`)}finally{clearInterval(progress);aiButton.disabled=false}}; window.pearlRunAI=()=>aiButton.onclick();
